// tokens.h - kept for reference only
// The actual token definitions and YYSTYPE come from y.tab.h (generated by bison).
// Do NOT include this file in the build; include y.tab.h instead.

// keywords
#define SELECT 1
#define FROM 2
#define WHERE 3
#define JOIN 4
#define ON 5
#define GROUP 6
#define BY 7
#define AS 8
#define AND 9
#define OR 10
#define NOT 11
#define HAVING 12

// operators
#define EQ 20
#define LT 21
#define GT 22
#define LEQ 23
#define GEQ 24
#define NEQ 25

// identifier / literal types
#define IDENTIFIER 30
#define INT_LITERAL 31
#define FLOAT_LITERAL 32
#define STRING_LITERAL 33